# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/rpi/os_customization/yocto/poky/meta \
  /home/rpi/os_customization/yocto/poky/meta-poky \
  /home/rpi/os_customization/yocto/poky/meta-yocto-bsp \
  /home/rpi/os_customization/yocto/poky/meta-customtesting-layer \
  /home/rpi/os_customization/yocto/poky/meta-raspberrypi \
  /home/rpi/os_customization/yocto/poky/meta-openembedded/meta-oe \
  /home/rpi/os_customization/yocto/poky/meta-openembedded/meta-python \
  /home/rpi/os_customization/yocto/poky/meta-openembedded/meta-networking \
  /home/rpi/os_customization/yocto/poky/meta-openembedded/meta-gnome \
  /home/rpi/os_customization/yocto/poky/meta-openembedded/meta-multimedia \
  /home/rpi/os_customization/yocto/poky/meta-openembedded/meta-xfce \
  /home/rpi/os_customization/yocto/poky/meta-my-layer \
  /home/rpi/os_customization/yocto/poky/meta-caminterface \
  /home/rpi/os_customization/yocto/poky/meta-clang \
  /home/rpi/os_customization/yocto/poky/meta-rust \
  /home/rpi/os_customization/yocto/poky/meta-browser/meta-chromium \
  "
