# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-arducam"
BBFILE_PATTERN_meta-arducam = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-arducam = "6"

LAYERDEPENDS_meta-arducam = "core"
LAYERSERIES_COMPAT_meta-arducam = "kirkstone"
