#include <stdio.h>


int main()
{
        printf("*********************************************************************\n");
        printf("*                                                                   *\n");
        printf("*            !! WELCOME TO CUSTOM OS ENVIRONMENT !!                 *\n");
        printf("*                                                                   *\n");
        printf("*                     Image created by                              *\n");                                                                                                                               printf("*                                                                   *\n");
        printf("*                       TEAM SMAC                                   *\n");
        printf("*                                                                   *\n");                                                                                                                               printf("*        #####################################################      *\n");                                                                                                                               printf("*        #                                                   #      *\n");                                                                                                                               printf("*        #   Built with vision. Delivered with purpose       #      *\n");                                                                                                                               printf("*        #   What we build today powers the world tomorrow   #      *\n");                                                                                                                               printf("*        #                                                   #      *\n");                                                                                                                               printf("*        #####################################################      *\n");                                                                                                                               printf("*                                                                   *\n");                                                                                                                               printf("*********************************************************************\n");                                                                                                                                                                                                                                                                                                                                                return 0;                                                                                                                                                                                                }      
