# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-interface"
BBFILE_PATTERN_meta-interface = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-interface = "6"

LAYERDEPENDS_meta-interface = "core"
LAYERSERIES_COMPAT_meta-interface = "kirkstone"
