# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-poky \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-yocto-bsp \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-raspberrypi \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-oe \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-python \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-networking \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-gnome \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-perl \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-multimedia \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-xfce \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-filesystems \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-initramfs \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-openembedded/meta-webserver \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-qt5 \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-analog \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-custom \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-virtualization \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-iris-thirdparty \
  /home/jasminpoc/Analog_OS/custom_os/nanbield/poky/meta-faceblur \
  "
